[package]
name = "tf-engine"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[lib]
name = "tf"

[dependencies]
boolinator = "2.4.0"
itertools = "0.7.8"
either = "1.5.0"
log = "0.4.6"

[dev-dependencies]
env_logger = "0.6.1"
