[package]
name = "typeflow-lang"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[lib]
name = "tfl"

[dependencies]
combine = "3.8.1"
tf-engine = { path = "../engine" }
